/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ClassBanner: typeof import('./components/class/ClassBanner.vue')['default']
    ClassMain: typeof import('./components/class/ClassMain.vue')['default']
    ClassSidebar: typeof import('./components/class/ClassSidebar.vue')['default']
    DefaultFooter: typeof import('./components/layouts/DefaultFooter.vue')['default']
    DefaultHeader: typeof import('./components/layouts/DefaultHeader.vue')['default']
    FormDemo: typeof import('./components/FormDemo.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HeroAdvice: typeof import('./components/home/HeroAdvice.vue')['default']
    HeroBanner: typeof import('./components/home/HeroBanner.vue')['default']
    HeroBrand: typeof import('./components/home/HeroBrand.vue')['default']
    HeroCarousel: typeof import('./components/home/HeroCarousel.vue')['default']
    HeroCourse: typeof import('./components/home/HeroCourse.vue')['default']
    HeroDesc: typeof import('./components/home/HeroDesc.vue')['default']
    MyLearningBanner: typeof import('./components/myLearning/MyLearningBanner.vue')['default']
    MyLearningDetail: typeof import('./components/myLearning/MyLearningDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBanner: typeof import('./components/search/SearchBanner.vue')['default']
    SearchList: typeof import('./components/search/SearchList.vue')['default']
  }
}
